### ISSUE TITLE
Fielding information should not be in a LUIS dialog

### ISSUE THREAD

**Issue by kevinleung23** [gcrev93/HannahHackathon#2]
LUIS is being hit with every entry from the user, including the text prompts for receiving Azure Codes. This should not be the case, as these are not queries LUIS needs to inspect. As a result, the LUIS model is being skewed.

This needs to be changed after this weekend (9/25)
Note: I have not reviewed @jcocchi #1 yet.

**Comment by kevinleung23** [comment]
@jcocchi this is why LUIS recognizes names as a `greeting` intent. The model has a lot of great queries, but needs to be scrubbed after this weekend.

**Comment by jcocchi** [comment]
@KSLHacks I agree that LUIS might not need to be hit while collecting the information, but what if the bot asks them for their name then they say "help" or "cancel," the bot should be able to recognize that new intent and reroute to a different dialog instead of continuing on in the form assuming "help" is their name. 
Because of this, LUIS would need to be hit in each stage of the form. The problem is (probably) that the current model is trained so that those answers like name are assigned to greeting. Instead, we should assign them to the azure code intent so that intent comes back as the top score for each stage of the form. This is implemented with trigger actions in my PR.
I'm open to discussion though, just something to think about!

**Comment by kevinleung23** [comment]
I think we agreed on this during the call. Moving forward we should make sure to not include those queries when training LUIS.
